// @vitest-environment node
import React from "react";
import { describe, expect, it } from "vitest";
import { Document, Page, Text, renderToBuffer } from "@react-pdf/renderer";
import { cleanExtractedText, extractTextFromPDF } from "@/lib/pdf-parser";

describe("PDF import compatibility", () => {
  it("reads real PDFs generated by the application's renderer, preserving page order", async () => {
    const buffer = await renderToBuffer(<Document>
      <Page><Text>Existing CV candidate. Built 12 projects.</Text></Page>
      <Page><Text>Education: Example University.</Text></Page>
    </Document>);
    const text = await extractTextFromPDF(buffer);
    expect(text).toContain("Built 12 projects.");
    expect(text).toContain("Education: Example University.");
    expect(text.indexOf("Existing CV")).toBeLessThan(text.indexOf("Education:"));
  });
  it("keeps section and bullet line breaks when cleaning extracted text", () => {
    expect(cleanExtractedText("  Experience\r\nBuilt   software\n\n\nEducation  ")).toBe("Experience\nBuilt software\n\nEducation");
  });
});
